//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGROcert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int Id { get; set; }
        public string AdmName { get; set; }
        public string AdmSurname { get; set; }
        public string AdmPhone { get; set; }
        public string AdmEmail { get; set; }
        public string AdmPassword { get; set; }
    }
}
